### ISSUE TITLE
Issue with car damages on ACC

### ISSUE THREAD

**Issue by Weshtrotinette** [hakanuzunoglu/TWF-Dash#1] opened 2023-04-14 12:37 UTC
When enabling :

"contextual_damage":1,
        "contextual_damage_tip": "Auto display a damage overlay in main MFD if your car receives damage. 1: Yes, 0: No",
        
The car always appear at left side without accident or damages on the car, maybe ACC is the script is not optimised for ACC. 

I disable this option to navigate manually to this tab when needed.

**Comment by hakanuzunoglu** [comment] 2023-04-14 13:09
Do you have a replay for this? It seems to work fine for me, i would like
to reproduce the problem if possible.

**Comment by hakanuzunoglu** [comment] 2023-04-14 15:18
Also, was it happening on beta version or the previous one? I just tested again and it works perfectly fine for me

**Comment by Weshtrotinette** [comment] 2023-04-14 16:52
![image](https://user-images.githubusercontent.com/126781656/232107255-87c81277-08e1-42da-9463-0843605476a6.png)

I'm in the pits just before going i got "Check your vehicle" and i can't change it because of his priority :/ 
but if i got damages or no damages this is always on :/ 

I've test on solo mode and online mode and the problem is the same :/

when i go out of track , the map open at right and return normal when i return on road, alright here

**Comment by Weshtrotinette** [comment] 2023-04-14 16:54
![image](https://user-images.githubusercontent.com/126781656/232107980-4d0188bc-593f-4820-bd14-46c25f4a928b.png)
 and when i'm driving

**Comment by hakanuzunoglu** [comment] 2023-04-14 18:52
So can you send me a simhub replay so i can reproduce it?

**Comment by hakanuzunoglu** [comment] 2023-04-17 02:07
I made some changes in the new version, please confirm if it is working as intended now. It was due to changed() function not being available to everyone. I included these functions within my dash as well.

**Comment by hakanuzunoglu** [comment] 2023-04-18 04:16
Closing due to no replies. Other users confirmed that this issue is fixed.

**Closed by hakanuzunoglu** 2023-04-18 04:16 UTC
